spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  sql:
    init:
      schema-locations: classpath:schema.sql
file:
  location: D:/spring/